// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwirtUcnn_ZI1qUo8FVjYNQFt3KCfIzJI',
    appId: '1:1051833034775:web:80cfc048d3255e6a6f5452',
    messagingSenderId: '1051833034775',
    projectId: 'car1wrgoo',
    authDomain: 'car1wrgoo.firebaseapp.com',
    databaseURL: 'https://car1wrgoo-default-rtdb.firebaseio.com',
    storageBucket: 'car1wrgoo.firebasestorage.app',
    measurementId: 'G-6WMPDMYKBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkHU-Pi7YXZ0LTbRWaaYECla74kzJW_1c',
    appId: '1:1051833034775:android:0d8f7a14c39037716f5452',
    messagingSenderId: '1051833034775',
    projectId: 'car1wrgoo',
    databaseURL: 'https://car1wrgoo-default-rtdb.firebaseio.com',
    storageBucket: 'car1wrgoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdgMj1RKdtUGIl0j2uYYAoOyU5e6CbuNc',
    appId: '1:1051833034775:ios:56933ad2e11e7e776f5452',
    messagingSenderId: '1051833034775',
    projectId: 'car1wrgoo',
    databaseURL: 'https://car1wrgoo-default-rtdb.firebaseio.com',
    storageBucket: 'car1wrgoo.firebasestorage.app',
    androidClientId: '1051833034775-074f7mus746pvaf9ob6aqa42hc5k2sjh.apps.googleusercontent.com',
    iosClientId: '1051833034775-fplu26kksdgbfgnhf08vg7ko7j4hncvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquarway',
  );

}